### ISSUE TITLE
Integrating KenLM with huggingface code

### ISSUE THREAD

**Issue by ramrahu** [Open-Speech-EkStep/vakyansh-wav2vec2-experimentation#12]
Hi,

I happened to come across your hindi model on huggingface recently. But I understand that the decoding script given on huggingface doesn't use the language model. Is there any way we can integrate a language model with that?

Kindly guide me to relevant resources for the same. Eagerly awaiting your response.

Thank you

**Comment by ankitasingh001** [comment]
You can use the  wav2vec wrapper https://github.com/Edresson/Wav2Vec-Wrapper for integrating language models .

**Comment by harveenchadha** [comment]
You should check this [PR](https://github.com/huggingface/transformers/pull/11606/files)

**Comment by harveenchadha** [comment]
This is now possible through Pyctcdecode. you can check the integration on HF website.
