### ISSUE TITLE
Time Stamps with Inference

### ISSUE THREAD

**Issue by nome2050** [Open-Speech-EkStep/vakyansh-wav2vec2-experimentation#13]
Is there any way I can get time stamps with the inference showing that which word or sentence was said during what time in the audio

**Comment by harveenchadha** [comment]
Yes there is one but the interpretation of this is not very easy.

You can check [here](https://github.com/pytorch/fairseq/pull/3627)

**Comment by harveenchadha** [comment]
This is now possible through Huggingface and pyctcdecode combination.
