### ISSUE TITLE
Params used for fine-tuning CLSRIL

### ISSUE THREAD

**Issue by ankitasingh001** [Open-Speech-EkStep/vakyansh-wav2vec2-experimentation#15]
Could you please provide the exact training scripts/ parameters (containing learning rates,etc) used for fine-tuning CLSRIL on various Indian languages for HuggingFace ? Stabilization seems to be an issue for me while training

**Comment by harveenchadha** [comment]
Hi Ankita,

We don't use HuggingFace, we use fairseq for finetuning. For training parameters you can check this config [here](https://github.com/Open-Speech-EkStep/vakyansh-wav2vec2-experimentation/blob/main/config/finetuning/base_100h.yaml)

**Comment by ankitasingh001** [comment]
Hi Harveen ,
Thanks for the reply ! Were the same params used for all languages ?

**Comment by harveenchadha** [comment]
We start training the model with default parameters first and most of the times we find the best  model with default parameters only.

The paramters do change with the size of the training corpus as you would have seen multiple configs like 10h, 100h, 1000h.

**Comment by ankitasingh001** [comment]
Thank you for the input , closing the issue
