### ISSUE TITLE
Inference with finetuned models 

### ISSUE THREAD

**Issue by pushkalkatara** [Open-Speech-EkStep/vakyansh-wav2vec2-experimentation#2]
Hi, 

I'm trying to run `english_finetuned_181h` model from [here](https://github.com/Open-Speech-EkStep/vakyansh-models) with the `single_file_inference.sh`. 

i used `generate_custom_model.sh` with updating the `finetuned_model_path` and `dictionary` with the ones provided on the link, which gave me error:
```
FileNotFoundError: [Errno 2] No such file or directory: './hindi_pretrain_4200_checkpoints_Nov2_Nov3/checkpoint_best_5967.pt'
```
I updated the `generate_custom_model.py` with hardcoded path which sort of resolved the issue. 
```
args.w2v_path = "vakyansh-wav2vec2-experimentation/scripts/inference/hindi_pretrained_4kh.pt"
```

Now I'm running the `single_file_inference.bash` with updated model path, dictionary, decoder as `kenlm` and the lm paths from the link above. I'm facing the following error:
```
bash single_file_inference.sh 
Traceback (most recent call last):
  File "../../utils/inference/single_file_inference.py", line 295, in <module>
    result = parse_transcription(args_local.model, args_local.dict, args_local.wav,  args_local.cuda, args_local.decoder, args_local.lexicon, args_local.lm_path)
  File "../../utils/inference/single_file_inference.py", line 272, in parse_transcription
    generator = W2lKenLMDecoder(args, target_dict)
  File "../../utils/inference/single_file_inference.py", line 137, in __init__
    ), f"{spelling} {spelling_idxs}"
AssertionError: ['व', 'र', 'ू', 'ण', 'क', 'र', '|'] [3, 3, 3, 3, 3, 3, 4]
```

What configs should i change for single wav inference?

**Comment by harveenchadha** [comment]
Hi, Please make sure that the language model you are using has the same dictionary as that of the trained model. You are trying to run a Hindi language model with English finetuned model, hence this error.

**Comment by singhaki** [comment]
@pushkalkatara i got the same error and followed the same steps by hardcoding w2v path. Model got generated but while inferencing it is giving blank output.

@harveenchadha  i also tried to convert the model to huggingface but it was giving random output.

In both the above cases i was using hindi_finetuned_4kh.pt, w2v_path = hindi_pretrained_4kh.pt

Any help would be great.

**Comment by harveenchadha** [comment]
Hi @singhaki 

Please let me know which model you tried to run inference on.

**Comment by singhaki** [comment]
@harveenchadha i have used hindi_finetuned_4kh.pt and used hindi_pretrained_4kh.pt as pretrained model for both generating custom model and generating hugging face model.

**Comment by harveenchadha** [comment]
@singhaki 

Can you please give it a try with this [branch](https://github.com/Open-Speech-EkStep/vakyansh-wav2vec2-experimentation/tree/v1). Note that the installation steps are a little different.

**Comment by harveenchadha** [comment]
Also Hugging face is a bit experimental at the moment. We are trying to make this commit stable. Once you confirm that the custom model is working with v1 branch, I would roll back v1 to main as this should be the ideal branch for your purpose.

Also we are in a process to make custom models available so that you do not need to generate them at your end.

https://github.com/Open-Speech-EkStep/vakyansh-models/issues/1

**Comment by harveenchadha** [comment]
Currently closing, if you face any issue please open again.

**Comment by Naramkeshav59** [comment]
I'm getting this error when inferencing using viterbi decoder
\
No such file or directory: '/data/Sougata/tech_intern/vakyansh-wav2vec2-experimentation/results/mini_librispeech/ref.word-checkpoint_best.pt-test.txt'
