### ISSUE TITLE
NameError: name 'CriterionType' is not defined

### ISSUE THREAD

**Issue by vpurandara** [Open-Speech-EkStep/vakyansh-wav2vec2-experimentation#32]
bash single_file_inference.sh

../../utils/inference/single_file_inference.py:29: UserWarning: flashlight python bindings are required to use this functionality. Please install from https://github.com/facebookresearch/flashlight/tree/master/bindings/python
  "flashlight python bindings are required to use this functionality. Please install from https://github.com/facebookresearch/flashlight/tree/master/bindings/python"
Traceback (most recent call last):
  File "../../utils/inference/single_file_inference.py", line 381, in <module>
    result = parse_transcription(args_local.model, args_local.dict, args_local.wav,  args_local.cuda, args_local.decoder, args_local.lexicon, args_local.lm_path, args_local.half)
  File "../../utils/inference/single_file_inference.py", line 348, in parse_transcription
    generator = W2lViterbiDecoder(args, target_dict)
  File "../../utils/inference/single_file_inference.py", line 143, in __init__
    super().__init__(args, tgt_dict)
  File "../../utils/inference/single_file_inference.py", line 84, in __init__
    self.criterion_type = CriterionType.CTC
NameError: name 'CriterionType' is not defined

Trying to run bash single_file_inference.sh but getting error related to flashlight. Searched for resolution but nothing helps. 

please can someone help me.

I tried reinstalling flashlight multiple times but getting the same issue everytime

**Comment by RajGothi** [comment]
@vpurandara @harveenchadha Can you please tell how you have solved this issue? I am also facing same issue. It would be great if you share the solution of it.
