### ISSUE TITLE
Error: 'dict' object has no attribute 'cuda'

### ISSUE THREAD

**Issue by sridhar1ga** [Open-Speech-EkStep/vakyansh-wav2vec2-experimentation#5]
Hello all
I'm trying to get the transcription for the vakyansh english model, but stuck with this error

```bash
$ bash single_file_inference.sh 
Traceback (most recent call last):
  File "../../utils/inference/single_file_inference.py", line 380, in <module>
    result = parse_transcription(args_local.model, args_local.dict, args_local.wav,  args_local.cuda, args_local.decoder, args_local.lexicon, args_local.lm_path, args_local.half)
  File "../../utils/inference/single_file_inference.py", line 355, in parse_transcription
    model.cuda()
AttributeError: 'dict' object has no attribute 'cuda'

```

**Comment by neerajchhimwal** [comment]
Hi, can you share your single_file_inference.sh file?

**Comment by sridhar1ga** [comment]
```bash
#dir=$PWD
#parentdir="$(dirname "$dir")"
#parentdir="$(dirname "$parentdir")"

### Values to change, if any ###
custom_model_path='/2expasr/ganesh/ekstep_mdls/eng/english_finetuned_181h.pt'
dictionary='/2expasr/ganesh/ekstep_mdls/eng/dict.ltr.txt'
wav_file_path="/database/ganesh/ganeshdbs/asr/11lng_my_dbc/train/english/tane_en/00008436.wav" # path to single wav file
decoder="viterbi" # viterbi or kenlm
cuda=True
half=False

#If kenlm
lm_name=''
lm_model_path='/2expasr/ganesh/ekstep_mdls/eng/lm.binary'
lexicon_lst_path='/2expasr/ganesh/ekstep_mdls/eng/lexicon.lst'

### Values to change end ###

if [ "$decoder" = "viterbi" ]
then
        python ../../utils/inference/single_file_inference.py -m ${custom_model_path} -d ${dictionary} -w ${wav_file_path} -c ${cuda} -D ${decoder} -H ${half}
else
        python ../../utils/inference/single_file_inference.py -m ${custom_model_path} -d ${dictionary} -w ${wav_file_path} -c ${cuda} -D ${decoder} -H ${half} -l ${lexicon_lst_path} -L ${lm_model_path}
fi

```

**Comment by harveenchadha** [comment]
Hi @sridhar1ga,

Kindly use the single model for inference as present here in the table:

https://github.com/Open-Speech-EkStep/vakyansh-models/blob/main/README.md#finetuned-models

Also please use v1 branch for setting up code:

https://github.com/Open-Speech-EkStep/vakyansh-wav2vec2-experimentation/tree/v1

**Comment by sridhar1ga** [comment]
Hello @harveenchadha, I ran using the v1 branch and the finetuned models and got this error
```bash
$ bash single_file_inference.sh 
  File "../../utils/inference/single_file_inference.py", line 137
    ), f"{spelling} {spelling_idxs}"
                                   ^
SyntaxError: invalid syntax
```

**Comment by neerajchhimwal** [comment]
Hi @sridhar1ga, I just ran single file inference using the v1 branch and "single model for inference" present [here](https://github.com/Open-Speech-EkStep/vakyansh-models/blob/main/README.md#finetuned-models) and it worked. Are you using the README instructions in v1 branch to create the environment?

**Comment by sridhar1ga** [comment]
Hi @neerajchhimwal, I've followed the installation instructions in v1 and used the "single model for inference" model.
```bash
$ git branch
* (HEAD detached at v1)
  main
```

**Comment by neerajchhimwal** [comment]
Hi @sridhar1ga, I'm not getting any syntax error while running. Can you try after cloning the repo again?

**Comment by harveenchadha** [comment]
@sridhar1ga 

This is an error related to f-string. https://www.geeksforgeeks.org/formatted-string-literals-f-strings-python/


Please make sure you are using Python 3.7 or above.

**Comment by sridhar1ga** [comment]
> Hi @sridhar1ga, I'm not getting any syntax error while running. Can you try after cloning the repo again?


Hi @neerajchhimwal, can u specify the commit on which you are running the code

> @sridhar1ga
> 
> This is an error related to f-string. [geeksforgeeks.org/formatted-string-literals-f-strings-python](https://www.geeksforgeeks.org/formatted-string-literals-f-strings-python/)
> 
> Please make sure you are using Python 3.7 or above.

Hi @harveenchadha, I'm using python 3.7 version as specified [here](https://github.com/Open-Speech-EkStep/vakyansh-wav2vec2-experimentation/tree/v1#installation-and-setup)

**Comment by neerajchhimwal** [comment]
@sridhar1ga, I'm on the latest commit on v1 branch

**Comment by neerajchhimwal** [comment]
Hi @sridhar1ga, were you able to infer?

**Comment by sridhar1ga** [comment]
Hi @neerajchhimwal
yes, but not able to infer with batch mode. can u please help me to solve this issue

**Comment by neerajchhimwal** [comment]
Sure, can you provide the error you're getting on running batch infer, and the file variables as well?

**Comment by sridhar1ga** [comment]
Hello @neerajchhimwal, Thank you, I found my error. I'm able to infer with batch mode
